@baseUrl = http://localhost:8000

### register
POST {{baseUrl}}/auth/register/
Content-Type: application/json

{
  "nom":"testNom",
  "prenom":"testPrenom",
  "email":"julien@test.com",
  "mdp":"ipl"
}

### Login avec Julien
POST {{baseUrl}}/auth/login/
Content-Type: application/json

{
  "email":"julien@test.com",
  "mdp":"ipl"
}

### vérifie le token
POST {{baseUrl}}/auth/verify-token/
Content-Type: application/json

{
  "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNTg4MDY2LCJpYXQiOjE3MzM1ODc3NjYsImp0aSI6IjMwYTI4MTA5ZjE0ZDRmNmI4NWI0NDM5MDJmNjc3Yzk3IiwidXNlcl9pZCI6Imp1bGllbkB0ZXN0LmNvbSJ9.A9XerL4DxoZWaOq3maNnQ6F7E-rFI-Fg1Bh7RpaqPi4"
}

### get un admin
GET {{baseUrl}}/auth/admin/julien@test.com/

